# Generated by Django 4.0.6 on 2022-07-29 22:49

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_titulo'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='post',
            managers=[
                ('objetos', django.db.models.manager.Manager()),
            ],
        ),
    ]
